import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import CardProvider from "@/context/CardProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <header className='px-5 py-2 flex justify-between gap-5 bg-stone-800 items-center'>
          <Link href='/'>
            <img src='/foodlogo.jpg' alt='' className='w-[120px]' />
          </Link>

          <div className='space-x-5'>
            <Link className='btn' href='/foods'>
              Foods
            </Link>
            <Link className='btn' href='/reviews'>
              Reviews
            </Link>
          </div>
        </header>

        <main className='px-10 py-10 flex-1'>
          <CardProvider>{children}</CardProvider>
        </main>
      </body>
    </html>
  );
}
